tap "hashicorp/tap"

# Shell
brew "fzf"
brew "tmux"

# Git
brew "git-filter-repo"
brew "gh"

# Infra
brew "ansible"
brew "helm"
brew "helmfile"
brew "kubernetes-cli"
brew "kubie"
brew "minikube"
brew "hashicorp/tap/terraform"
brew "terragrunt"

# Dev
brew "go"
brew "goenv"
brew "golangci-lint"
brew "hadolint"
brew "jq"
brew "ripgrep"
brew "tree"

# Site
brew "hugo"

# Fonts
cask "font-fira-code"
cask "font-jetbrains-mono"

# Mac apps
cask "hashicorp-vagrant"
cask "orbstack"
cask "utm"
